# Generated by Django 2.0.3 on 2018-04-08 18:33
# To reset migrations to initial:
# python3 manage.py migrate --fake snapcapapp 0001_initial

from django.db import migrations
from django.core.management import call_command

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'users', app_label='app')
    call_command('loaddata', 'profiles', app_label='app')
    call_command('loaddata', 'pictures', app_label='app')
    call_command('loaddata', 'friends', app_label='app')
    call_command('loaddata', 'usercaps', app_label='app')
    call_command('loaddata', 'votes_picture', app_label='app')
    call_command('loaddata', 'votes_caption', app_label='app')

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
