# Generated by Django 2.0.3 on 2018-04-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180408_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='category',
            field=models.CharField(choices=[('animals', 'animals'), ('cats', 'cats'), ('dogs', 'dogs'), ('sports', 'sports'), ('hummus', 'hummus')], max_length=20),
        ),
    ]
