# Generated by Django 2.0.3 on 2018-04-09 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180409_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercap',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercaps', to='app.Picture'),
        ),
    ]
