# Generated by Django 2.0.3 on 2018-04-10 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180409_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercap',
            name='votes',
        ),
        migrations.AddField(
            model_name='vote_caption',
            name='usercap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Usercap'),
            preserve_default=False,
        ),
    ]
