# Generated by Django 2.0.3 on 2018-04-11 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180410_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='uploaded_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
